# Generated by Django 5.0.4 on 2024-05-04 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('users', '0003_alter_userprofile_role_alter_userprofile_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='submission',
        ),
        migrations.AddField(
            model_name='submission',
            name='semester',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='base.submission')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='base.topic'),
        ),
        migrations.CreateModel(
            name='UserChatM2m',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
    ]
