# Generated by Django 5.0.4 on 2024-05-04 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_file_submission_submission_semester_topic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='file',
            old_name='created_at',
            new_name='upload_date',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='submission',
        ),
        migrations.AddField(
            model_name='file',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='base.submission'),
        ),
        migrations.AddField(
            model_name='submission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='research_work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.researchwork'),
        ),
        migrations.AddField(
            model_name='topic',
            name='research_work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='base.researchwork'),
        ),
    ]
