# Generated by Django 5.0.4 on 2024-06-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_assignment_text_alter_submission_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
