# Generated by Django 5.0.4 on 2024-06-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_assignment_is_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
