# Generated by Django 5.0.4 on 2024-06-11 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_file_is_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='file_comment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_comment', to='base.file'),
        ),
    ]
