# Generated by Django 5.0.4 on 2024-06-11 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_file_comment_alter_comment_file_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
