# Generated by Django 5.1.2 on 2024-11-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_semester_remove_file_submission_remove_file_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='semester_type',
            field=models.CharField(choices=[('Spring', 'Весенний семестр'), ('Fall', 'Осенний семестр')], editable=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_name',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
