# Generated by Django 5.1.2 on 2024-11-17 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_semester_semester_type_alter_semester_semester_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.semester'),
        ),
    ]
